export const SET_SYNC_STATE = "SET_SYNC_STATE";
export const SELECT_CHANNEL = "SELECT_CHANNEL";
export const ADD_CHANNEL = "ADD_CHANNEL";
export const ADD_CHANNEL_BEGIN = "ADD_CHANNEL_BEGIN";
export const ADD_CHANNEL_END = "ADD_CHANNEL_END";
export const SET_CHANNELS = "SET_CHANNELS";
export const ADD_CHANNEL_ERROR = "ADD_CHANNEL_ERROR";
export const SET_CURRENT_FEEDS_BEGIN = "SET_CURRENT_FEEDS_BEGIN";
export const SET_CURRENT_FEEDS = "SET_CURRENT_FEEDS";
export const DELETE_CHANNELS = "DELETE_CHANNELS";
export const MOVE_CHANNEL = "MOVE_CHANNEL";
export const UPDATE_CHANNEL_FEED = "UPDATE_CHANNEL_FEED";
export const SET_FEED_READ_STATUS = "GET_FEED_READ_STATUS";
export const OPEN_FEED = "OPEN_FEED";
export const CLOSE_FEED = "CLOSE_FEED";
export const SCROLL_FEED_CONTENT = "SCROLL_FEED_CONTENT";

export const OPEN_ACTION_MENU = "OPEN_ACTION_MENU";
export const CLOSE_ACTION_MENU = "CLOSE_ACTION_MENU";
export const SET_CHANNEL_SELECTOR_EDITMODE = "CLOSE_CHANNEL_SELECTOR_EDITMODE";
export const TOGGLE_CHANNEL_SELECTOR_EDITMODE = "TOGGLE_CHANNEL_SELECTOR_EDITMODE";

export const SET_SETTINGS = "SET_SETTINGS";
export const SET_DEFAULT_STATE = "SET_DEFAULT_STATE";
export const CONNECT_BACKGROUND = "CONNECT_BACKGROUND";
export const BACKGROUND_UPDATE_CHANNEL = "BACKGROUND_UPDATE_CHANNEL";
export const CLEAN_CACHE = "CLEAN_CACHE";
export const UPDATE_LAST_ACTIVE_TIME = "UPDATE_LAST_ACTIVE_TIME";
export const GO_BACK_LAST_READ = "GO_BACK_LAST_READ";
export const DELETE_LAST_READ = "DELETE_LAST_READ";
export const CLOSE_MESSAGE_BAR = "CLOSE_MESSAGE_BAR";

export const SET_COMPONENT_STATE = "SET_COMPONENT_STATE";
export const LOG = "LOG";