export const SET_INIT_STATE = "SET_INIT_STATE";
export const SELECT_CHANNEL = "SELECT_CHANNEL";
export const ADD_CHANNEL = "ADD_CHANNEL";
export const SET_CHANNELS = "SET_CHANNELS";
export const DELETE_CHANNELS = "DELETE_CHANNELS";
export const UPDATE_CHANNEL_FEED = "UPDATE_CHANNEL_FEED";
export const RECEIVE_FEED = "RECEIVE_FEED";
export const SET_FEED_READ_STATUS = "GET_FEED_READ_STATUS";
export const OPEN_FEED = "OPEN_FEED";
export const CLOSE_FEED = "CLOSE_FEED";
export const UPDATE_UNREAD_COUNT = "UPDATE_UNREAD_COUNT";

export const OPEN_ACTION_MENU = "OPEN_ACTION_MENU";
export const CLOSE_ACTION_MENU = "CLOSE_ACTION_MENU";
export const SET_CHANNEL_SELECTOR_EDITMODE = "CLOSE_CHANNEL_SELECTOR_EDITMODE";
export const TOGGLE_CHANNEL_SELECTOR_EDITMODE = "TOGGLE_CHANNEL_SELECTOR_EDITMODE";

export const SET_SETTINGS = "SET_SETTINGS";