export const ADD_CHANNEL = "ADD_CHANNEL";
export const SET_CHANNELS = "SET_CHANNELS";
export const DELETE_CHANNELS = "DELETE_CHANNELS";
export const UPDATE_UNREAD_COUNT = "UPDATE_UNREAD_COUNT";

export const SET_CHANNEL_SELECTOR_EDITMODE = "CLOSE_CHANNEL_SELECTOR_EDITMODE";
export const TOGGLE_CHANNEL_SELECTOR_EDITMODE = "TOGGLE_CHANNEL_SELECTOR_EDITMODE";